name: ar_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin_2: ^0.0.3
  vector_math: ^2.1.4
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.8
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  flutter_login: ^5.0.0
  dashboard: ^0.0.4
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
